import delay from "@trendyminds/delay";

(async () => {
  // Let's wait a bit. We're not a critical process for the page to load so let's delay execution by an arbitrary amount of time
  await delay(1000);

  // Insert the result of the request into the DOM
  const res = await fetch("/actions/visor/default/access");

  // If we encountered an error loading the Visor material just exit out
  // if (res.status !== 200) {
  //   return false;
  // }

  // Get the HTML generated by the template
  const data = await res.text();

  // If we have any data to return, insert it into the bottom of the document
  if (data) {
    document.body.insertAdjacentHTML("beforeend", data);
    import("./init").then((module) => new module.default());
  }
})();
